version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ../../database/schema:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: bdjuno
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_mechain"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  hasura:
    image: hasura/graphql-engine:v2.0.4
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  bdjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bdjuno parse --home /bdjuno/.bdjuno
    volumes:
      ## Modify first path to match configuration file.
      - /bdjuno/.bdjuno:/bdjuno/.bdjuno
